/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include "std_types.h"
#include "rcc.h"
#include "gpio.h"
#include "nvic.h"
#include "exti.h"
#include "syscfg.h"


void Exti13(void);


int main(void)
{
	/* Enable clock */
	RCC_AHB1_enableClock(RCC_AHB1_GPIOA);
	RCC_AHB1_enableClock(RCC_AHB1_GPIOC);
	RCC_APB2_enableClock(RCC_APB2_SYSCFG);

	/* Initialize GPIO pins */
	GPIO_PinConfig_Type s_pinA5Config = {.Port = GPIO_PORTA,
										 .PinNum = GPIO_PIN5,
										 .PinMode = GPIO_OUTPUT,
										 .PullStatus = GPIO_PULLDOWN,
										 .OutputSpeed = GPIO_OUT_LOW_SPEED,
										 .OutputType = GPIO_OUT_PUSH_PULL,
										 .AltFunc = GPIO_AF_NA};
	GPIO_pinInit(&s_pinA5Config);

	GPIO_PinConfig_Type s_pinC13Config = {.Port = GPIO_PORTC,
										  .PinNum = GPIO_PIN13,
										  .PinMode = GPIO_INPUT,
										  .PullStatus = GPIO_NOPULL,
										  .OutputSpeed = GPIO_OUT_SPEED_NA,
									  	  .OutputType = GPIO_OUT_TYPE_NA,
										  .AltFunc = GPIO_AF_NA};
	GPIO_pinInit(&s_pinC13Config);

	/* Initialize external interrupt */
	SYSCFG_EXTIPort(SYSCFG_EXTI_PORTC, SYSCFG_GPIO13);

	EXTI_lineInterruptConfig_Type s_extIPinC13Config = {.Line = EXTI13,
														.Trigger = EXTI_FALLING_TRIGGER,
														.callBackFunc = Exti13};

	EXTI_interruptInit(&s_extIPinC13Config);

	/* Enable interrupt in NVIC */
	NVIC_enableIRQ(EXTI15_10_IRQ);

    /* Loop forever */
	for(;;);
}


/* CallBack Handler */
void Exti13(void)
{
	GPIO_togglePinValue(GPIO_PORTA, GPIO_PIN5);
}
